import 'package:e_mart/consts/consts.dart';
import 'package:e_mart/models/category_model.dart';
import 'package:e_mart/models/product_model.dart';
import 'package:e_mart/models/store_model.dart';

const socialIconList = [icFacebookLogo, icGoogleLogo, icTwitterLogo];

const sliderLists = [imgSlider1, imgSlider2, imgSlider3, imgSlider4];

const secondSliderList = [imgSs1, imgSs2, imgSs3, imgSs4];

// Categories with images combined
const categoriesData = [
  Category(key: 'womenClothing', name: womenClothing, image: imgFc8),
  Category(key: 'menClothingFashion', name: menClothingFashion, image: imgFc1),
  Category(key: 'compAccess', name: compAccess, image: imgFc2),
  Category(key: 'kidtoys', name: kidtoys, image: imgFc4),
  Category(key: 'automobile', name: automobile, image: imgFc3),
  Category(key: 'sports', name: sports, image: imgFc5),
  Category(key: 'jewelery', name: jewelery, image: imgFc7),
  Category(key: 'cellphone', name: cellphone, image: imgFc6),
  Category(key: 'furniture', name: furniture, image: imgFc9),
];

const itemDetailButtonList = [
  video,
  reviews,
  privacyPolicy,
  returnPolicy,
  supportPolicy,
];

// Dummy Stores for E-mart App
final dummyStores = [
  Store(
    userId: 'emart-central',
    name: 'E-Mart Central',
    description:
        'Flagship store with curated electronics, home essentials, and daily deals.',
    ownerName: 'E-Mart Official',
    logo: icShop,
    coverImage: imgSlider1,
    phone: '+84 28 5550 1000',
    email: 'central@emart.example',
    address: '72 Le Thanh Ton, District 1, Ho Chi Minh City',
    openingHours: 'Mon - Sun, 8:00 AM - 10:00 PM',
    rating: 4.8,
    followerCount: 12800,
    productCount: 5,
    latitude: 10.7769,
    longitude: 106.7009,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Store(
    userId: 'style-hub',
    name: 'Style Hub',
    description:
        'Fashion store for everyday outfits, footwear, and accessories.',
    ownerName: 'Style Hub Team',
    logo: icFavoriteSeller,
    coverImage: imgSlider2,
    phone: '+84 28 5550 2200',
    email: 'hello@stylehub.example',
    address: '191 Hai Ba Trung, District 3, Ho Chi Minh City',
    openingHours: 'Mon - Sat, 9:00 AM - 9:00 PM',
    rating: 4.6,
    followerCount: 8400,
    productCount: 3,
    latitude: 10.7893,
    longitude: 106.6917,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Store(
    userId: 'home-play',
    name: 'Home & Play',
    description:
        'Trusted seller for furniture, children products, sports, and lifestyle gear.',
    ownerName: 'Home & Play Co.',
    logo: icTopSeller,
    coverImage: imgSlider3,
    phone: '+84 28 5550 3300',
    email: 'support@homeplay.example',
    address: '45 Nguyen Hue, District 1, Ho Chi Minh City',
    openingHours: 'Mon - Sun, 8:30 AM - 9:30 PM',
    rating: 4.7,
    followerCount: 9600,
    productCount: 4,
    latitude: 10.7735,
    longitude: 106.7042,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];

Store storeByUserId(String storeUserId) {
  return dummyStores.firstWhere(
    (store) => store.userId == storeUserId,
    orElse: () => dummyStores.first,
  );
}

List<Product> productsByStore(String storeId) {
  return dummyProducts.where((product) => product.storeId == storeId).toList();
}

// Dummy Products for E-mart App
final dummyProducts = [
  // Featured Products
  Product(
    id: '1',
    name: 'Premium Wireless Headphones',
    description:
        'High-quality wireless headphones with noise cancellation and 30-hour battery life.',
    category: 'cellphone',
    price: 79.99,
    originalPrice: 129.99,
    images: [imgP1],
    storeId: 'emart-central',
    rating: 4.5,
    reviewCount: 320,
    stock: 45,
    isFeatured: true,
    isNew: true,
    colors: ['Black', 'White', 'Blue'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Product(
    id: '2',
    name: 'Smart Watch Series 5',
    description:
        'Advanced fitness tracking with heart rate monitor and sleep analysis.',
    category: 'cellphone',
    price: 199.99,
    originalPrice: 299.99,
    images: [imgP2],
    storeId: 'emart-central',
    rating: 4.8,
    reviewCount: 567,
    stock: 32,
    isFeatured: true,
    isNew: true,
    colors: ['Silver', 'Black', 'Gold'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Product(
    id: '3',
    name: 'Ergonomic Office Chair',
    description:
        'Premium ergonomic chair with lumbar support and adjustable armrests.',
    category: 'furniture',
    price: 249.99,
    originalPrice: 399.99,
    images: [imgP3],
    storeId: 'home-play',
    rating: 4.3,
    reviewCount: 245,
    stock: 18,
    isFeatured: true,
    isNew: false,
    colors: ['Black', 'Grey', 'Brown'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Product(
    id: '4',
    name: 'Professional USB-C Hub',
    description: '7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader.',
    category: 'compAccess',
    price: 49.99,
    originalPrice: 79.99,
    images: [imgP4],
    storeId: 'emart-central',
    rating: 4.6,
    reviewCount: 189,
    stock: 60,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    isFeatured: true,
    isNew: true,
  ),
  Product(
    id: '5',
    name: 'Sports Running Shoes',
    description:
        'Lightweight running shoes with advanced cushioning technology.',
    category: 'sports',
    price: 89.99,
    originalPrice: 139.99,
    images: [imgP5],
    storeId: 'style-hub',
    rating: 4.4,
    reviewCount: 412,
    stock: 55,
    isFeatured: true,
    isNew: false,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    colors: ['Red', 'Black', 'White'],
  ),
  Product(
    id: '6',
    name: 'Sterling Silver Necklace',
    description: 'Elegant 925 sterling silver necklace with adjustable chain.',
    category: 'jewelery',
    price: 45.99,
    originalPrice: 89.99,
    images: [imgP6],
    storeId: 'style-hub',
    rating: 4.7,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    reviewCount: 234,
    stock: 28,
    isFeatured: true,
    isNew: false,
  ),

  // Regular Products
  Product(
    id: '7',
    name: 'Casual Cotton T-Shirt',
    description:
        '100% organic cotton, comfortable fit, available in multiple colors.',
    category: 'womenClothing',
    price: 19.99,
    originalPrice: 34.99,
    images: [imgP7],
    storeId: 'style-hub',
    rating: 4.2,
    reviewCount: 145,
    stock: 120,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    isFeatured: false,
    isNew: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Pink', 'Blue'],
  ),
  Product(
    id: '8',
    name: 'Denim Blue Jeans',
    description: 'Classic fit denim jeans with fade-resistant material.',
    category: 'menClothingFashion',
    price: 59.99,
    originalPrice: 99.99,
    images: [imgP1],
    storeId: 'style-hub',
    rating: 4.5,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    reviewCount: 328,
    stock: 85,
    isFeatured: false,
    isNew: false,
    sizes: ['28', '30', '32', '34', '36', '38'],
    colors: ['Dark Blue', 'Light Blue', 'Black'],
  ),
  Product(
    id: '9',
    name: 'Kids Educational Toy Set',
    description: 'Safe and educational toy set for children ages 3+.',
    category: 'kidtoys',
    price: 34.99,
    originalPrice: 59.99,
    images: [imgP2],
    storeId: 'home-play',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    rating: 4.6,
    reviewCount: 267,
    stock: 42,
    isFeatured: false,
    isNew: true,
    attributes: {'ageRange': '3-8 years', 'pieces': '50+'},
  ),
  Product(
    id: '10',
    name: 'Motorcycle Helmet',
    description: 'DOT certified safety helmet with ventilation system.',
    category: 'automobile',
    price: 129.99,
    originalPrice: 199.99,
    images: [imgP3],
    storeId: 'emart-central',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    rating: 4.4,
    reviewCount: 156,
    stock: 24,
    isFeatured: false,
    isNew: false,
    colors: ['Black', 'White', 'Red'],
  ),
  Product(
    id: '11',
    name: 'Yoga Mat Premium',
    description: 'Non-slip yoga mat with carrying strap, 6mm thickness.',
    category: 'sports',
    price: 29.99,
    originalPrice: 49.99,
    images: [imgP4],
    storeId: 'home-play',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    rating: 4.3,
    reviewCount: 189,
    stock: 67,
    isFeatured: false,
    isNew: true,
    colors: ['Purple', 'Black', 'Blue', 'Pink'],
  ),
  Product(
    id: '12',
    name: 'Wooden Dining Table',
    description: 'Solid oak wood dining table with room for 6 chairs.',
    category: 'furniture',
    price: 399.99,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    originalPrice: 649.99,
    images: [imgP5],
    storeId: 'home-play',
    rating: 4.7,
    reviewCount: 98,
    stock: 12,
    isFeatured: false,
    isNew: false,
    attributes: {'material': 'Oak Wood', 'capacity': '6 persons'},
  ),
  Product(
    id: '13',
    name: 'Linen Summer Dress',
    description:
        'Breathable linen blend dress with a relaxed silhouette for warm days.',
    category: 'womenClothing',
    price: 54.99,
    originalPrice: 89.99,
    images: [imgFc8],
    rating: 4.6,
    reviewCount: 214,
    stock: 36,
    isFeatured: true,
    isNew: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Blue', 'Pink'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'material': 'Linen blend', 'fit': 'Relaxed'},
  ),
  Product(
    id: '14',
    name: 'Classic Blazer Jacket',
    description:
        'Structured blazer with a clean single-button front and soft lining.',
    category: 'womenClothing',
    price: 74.99,
    originalPrice: 119.99,
    images: [imgB4],
    rating: 4.4,
    reviewCount: 168,
    stock: 22,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'White', 'Brown'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'material': 'Polyester blend', 'style': 'Business casual'},
  ),
  Product(
    id: '15',
    name: 'Oxford Button-Down Shirt',
    description:
        'Soft cotton oxford shirt designed for office days and weekend wear.',
    category: 'menClothingFashion',
    price: 39.99,
    originalPrice: 64.99,
    images: [imgFc1],
    rating: 4.5,
    reviewCount: 286,
    stock: 58,
    isFeatured: true,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Blue', 'Black'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'material': 'Cotton', 'fit': 'Regular'},
  ),
  Product(
    id: '16',
    name: 'Slim Fit Chinos',
    description:
        'Stretch cotton chinos with a tapered leg and everyday comfort.',
    category: 'menClothingFashion',
    price: 49.99,
    originalPrice: 79.99,
    images: [imgB2],
    rating: 4.3,
    reviewCount: 174,
    stock: 64,
    sizes: ['28', '30', '32', '34', '36', '38'],
    colors: ['Black', 'Brown', 'Grey'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'material': 'Stretch cotton', 'fit': 'Slim'},
  ),
  Product(
    id: '17',
    name: 'Mechanical Keyboard RGB',
    description:
        'Compact mechanical keyboard with tactile switches and customizable RGB.',
    category: 'compAccess',
    price: 89.99,
    originalPrice: 129.99,
    images: [imgFc2],
    rating: 4.8,
    reviewCount: 521,
    stock: 40,
    isFeatured: true,
    isNew: true,
    colors: ['Black', 'White'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'layout': '75%', 'connection': 'USB-C'},
  ),
  Product(
    id: '18',
    name: 'Wireless Ergonomic Mouse',
    description:
        'Rechargeable ergonomic mouse with silent clicks and adjustable DPI.',
    category: 'compAccess',
    price: 34.99,
    originalPrice: 54.99,
    images: [imgS8],
    rating: 4.4,
    reviewCount: 303,
    stock: 73,
    colors: ['Black', 'Silver'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'battery': '45 days', 'dpi': '800-2400'},
  ),
  Product(
    id: '19',
    name: 'Remote Control Race Car',
    description:
        'Fast rechargeable RC car with shockproof wheels and easy steering.',
    category: 'kidtoys',
    price: 42.99,
    originalPrice: 69.99,
    images: [imgFc4],
    rating: 4.5,
    reviewCount: 197,
    stock: 38,
    isNew: true,
    colors: ['Red', 'Blue'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'ageRange': '6+ years', 'battery': 'Rechargeable'},
  ),
  Product(
    id: '20',
    name: 'Wooden Puzzle Blocks',
    description:
        'Colorful wooden blocks that support early learning and motor skills.',
    category: 'kidtoys',
    price: 24.99,
    originalPrice: 39.99,
    images: [imgB7],
    rating: 4.7,
    reviewCount: 132,
    stock: 51,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'ageRange': '2-5 years', 'pieces': '36'},
  ),
  Product(
    id: '21',
    name: 'Car Vacuum Cleaner',
    description:
        'Portable high-suction vacuum cleaner for seats, carpets, and trunks.',
    category: 'automobile',
    price: 59.99,
    originalPrice: 89.99,
    images: [imgFc3],
    rating: 4.2,
    reviewCount: 118,
    stock: 30,
    colors: ['Black'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'power': '120W', 'filter': 'HEPA'},
  ),
  Product(
    id: '22',
    name: 'Dashboard Phone Mount',
    description:
        'Adjustable phone mount with strong suction and 360-degree rotation.',
    category: 'automobile',
    price: 18.99,
    originalPrice: 29.99,
    images: [imgS9],
    rating: 4.4,
    reviewCount: 267,
    stock: 95,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'compatibility': '4-7 inch phones', 'rotation': '360 degrees'},
  ),
  Product(
    id: '23',
    name: 'Adjustable Dumbbell Set',
    description:
        'Space-saving dumbbell set with quick weight adjustment for home gyms.',
    category: 'sports',
    price: 149.99,
    originalPrice: 219.99,
    images: [imgFc5],
    rating: 4.7,
    reviewCount: 342,
    stock: 16,
    isFeatured: true,
    colors: ['Black', 'Silver'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'weightRange': '5-25 kg', 'material': 'Steel'},
  ),
  Product(
    id: '24',
    name: 'Insulated Sports Bottle',
    description:
        'Double-wall stainless steel bottle that keeps drinks cold for hours.',
    category: 'sports',
    price: 21.99,
    originalPrice: 34.99,
    images: [imgS11],
    rating: 4.6,
    reviewCount: 421,
    stock: 88,
    colors: ['Black', 'Blue', 'Pink'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'capacity': '750 ml', 'material': 'Stainless steel'},
  ),
  Product(
    id: '25',
    name: 'Pearl Drop Earrings',
    description:
        'Minimal pearl earrings with a polished finish for everyday elegance.',
    category: 'jewelery',
    price: 32.99,
    originalPrice: 59.99,
    images: [imgFc7],
    rating: 4.8,
    reviewCount: 203,
    stock: 44,
    isNew: true,
    colors: ['Gold', 'Silver'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'material': 'Alloy', 'closure': 'Push back'},
  ),
  Product(
    id: '26',
    name: 'Minimal Gold Bracelet',
    description:
        'Layer-friendly bracelet with adjustable chain and refined details.',
    category: 'jewelery',
    price: 38.99,
    originalPrice: 74.99,
    images: [imgPi4],
    rating: 4.5,
    reviewCount: 151,
    stock: 37,
    colors: ['Gold'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'length': '16-20 cm', 'finish': 'Polished'},
  ),
  Product(
    id: '27',
    name: 'Android Tablet 10 Inch',
    description:
        'Lightweight tablet with vivid display, long battery life, and stereo speakers.',
    category: 'cellphone',
    price: 229.99,
    originalPrice: 329.99,
    images: [imgFc6],
    rating: 4.4,
    reviewCount: 359,
    stock: 29,
    isFeatured: true,
    colors: ['Black', 'Silver'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'storage': '128 GB', 'display': '10.1 inch'},
  ),
  Product(
    id: '28',
    name: 'Fast Charging Power Bank',
    description:
        'Compact 20000mAh power bank with USB-C fast charging support.',
    category: 'cellphone',
    price: 44.99,
    originalPrice: 69.99,
    images: [imgS10],
    rating: 4.6,
    reviewCount: 612,
    stock: 77,
    colors: ['Black', 'White'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'capacity': '20000 mAh', 'ports': 'USB-C, USB-A'},
  ),
  Product(
    id: '29',
    name: 'Modern Floor Lamp',
    description:
        'Slim floor lamp with warm lighting for living rooms and bedrooms.',
    category: 'furniture',
    price: 84.99,
    originalPrice: 139.99,
    images: [imgFc9],
    rating: 4.3,
    reviewCount: 96,
    stock: 20,
    colors: ['Black', 'Gold'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'height': '160 cm', 'bulb': 'E27 LED'},
  ),
  Product(
    id: '30',
    name: 'Storage Coffee Table',
    description:
        'Compact coffee table with hidden storage and scratch-resistant finish.',
    category: 'furniture',
    price: 129.99,
    originalPrice: 199.99,
    images: [imgB9],
    rating: 4.5,
    reviewCount: 127,
    stock: 14,
    colors: ['Brown', 'White'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    attributes: {'material': 'Engineered wood', 'storage': 'Hidden shelf'},
  ),
];

const profileButtonsList = [orders, wishList, messages];
const profileButtonImages = [icOrder, icOrder, icMessages];
