import 'package:e_mart/consts/consts.dart';
import 'package:e_mart/models/category_model.dart';
import 'package:e_mart/models/product_model.dart';

const socialIconList = [icFacebookLogo, icGoogleLogo, icTwitterLogo];

const sliderLists = [imgSlider1, imgSlider2, imgSlider3, imgSlider4];

const secondSliderList = [imgSs1, imgSs2, imgSs3, imgSs4];

// Categories with images combined
const categoriesData = [
  Category(name: womenClothing, image: imgFc8),
  Category(name: menClothingFashion, image: imgFc1),
  Category(name: compAccess, image: imgFc2),
  Category(name: kidtoys, image: imgFc4),
  Category(name: automobile, image: imgFc3),
  Category(name: sports, image: imgFc5),
  Category(name: jewelery, image: imgFc7),
  Category(name: cellphone, image: imgFc6),
  Category(name: furniture, image: imgFc9),
];

const itemDetailButtonList = [
  video,
  reviews,
  privacyPolicy,
  returnPolicy,
  supportPolicy,
];

// Dummy Products for E-mart App
final dummyProducts = [
  // Featured Products
  Product(
    id: '1',
    name: 'Premium Wireless Headphones',
    description:
        'High-quality wireless headphones with noise cancellation and 30-hour battery life.',
    category: 'cellphone',
    price: 79.99,
    originalPrice: 129.99,
    images: [imgP1],
    rating: 4.5,
    reviewCount: 320,
    stock: 45,
    isFeatured: true,
    isNew: true,
    colors: ['Black', 'White', 'Blue'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Product(
    id: '2',
    name: 'Smart Watch Series 5',
    description:
        'Advanced fitness tracking with heart rate monitor and sleep analysis.',
    category: 'cellphone',
    price: 199.99,
    originalPrice: 299.99,
    images: [imgP2],
    rating: 4.8,
    reviewCount: 567,
    stock: 32,
    isFeatured: true,
    isNew: true,
    colors: ['Silver', 'Black', 'Gold'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Product(
    id: '3',
    name: 'Ergonomic Office Chair',
    description:
        'Premium ergonomic chair with lumbar support and adjustable armrests.',
    category: 'furniture',
    price: 249.99,
    originalPrice: 399.99,
    images: [imgP3],
    rating: 4.3,
    reviewCount: 245,
    stock: 18,
    isFeatured: true,
    isNew: false,
    colors: ['Black', 'Grey', 'Brown'],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Product(
    id: '4',
    name: 'Professional USB-C Hub',
    description: '7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader.',
    category: 'compAccess',
    price: 49.99,
    originalPrice: 79.99,
    images: [imgP4],
    rating: 4.6,
    reviewCount: 189,
    stock: 60,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    isFeatured: true,
    isNew: true,
  ),
  Product(
    id: '5',
    name: 'Sports Running Shoes',
    description:
        'Lightweight running shoes with advanced cushioning technology.',
    category: 'sports',
    price: 89.99,
    originalPrice: 139.99,
    images: [imgP5],
    rating: 4.4,
    reviewCount: 412,
    stock: 55,
    isFeatured: true,
    isNew: false,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    colors: ['Red', 'Black', 'White'],
  ),
  Product(
    id: '6',
    name: 'Sterling Silver Necklace',
    description: 'Elegant 925 sterling silver necklace with adjustable chain.',
    category: 'jewelery',
    price: 45.99,
    originalPrice: 89.99,
    images: [imgP6],
    rating: 4.7,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    reviewCount: 234,
    stock: 28,
    isFeatured: true,
    isNew: false,
  ),

  // Regular Products
  Product(
    id: '7',
    name: 'Casual Cotton T-Shirt',
    description:
        '100% organic cotton, comfortable fit, available in multiple colors.',
    category: 'womenClothing',
    price: 19.99,
    originalPrice: 34.99,
    images: [imgP7],
    rating: 4.2,
    reviewCount: 145,
    stock: 120,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    isFeatured: false,
    isNew: true,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'White', 'Pink', 'Blue'],
  ),
  Product(
    id: '8',
    name: 'Denim Blue Jeans',
    description: 'Classic fit denim jeans with fade-resistant material.',
    category: 'menClothingFashion',
    price: 59.99,
    originalPrice: 99.99,
    images: [imgP1],
    rating: 4.5,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    reviewCount: 328,
    stock: 85,
    isFeatured: false,
    isNew: false,
    sizes: ['28', '30', '32', '34', '36', '38'],
    colors: ['Dark Blue', 'Light Blue', 'Black'],
  ),
  Product(
    id: '9',
    name: 'Kids Educational Toy Set',
    description: 'Safe and educational toy set for children ages 3+.',
    category: 'kidtoys',
    price: 34.99,
    originalPrice: 59.99,
    images: [imgP2],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    rating: 4.6,
    reviewCount: 267,
    stock: 42,
    isFeatured: false,
    isNew: true,
    attributes: {'ageRange': '3-8 years', 'pieces': '50+'},
  ),
  Product(
    id: '10',
    name: 'Motorcycle Helmet',
    description: 'DOT certified safety helmet with ventilation system.',
    category: 'automobile',
    price: 129.99,
    originalPrice: 199.99,
    images: [imgP3],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    rating: 4.4,
    reviewCount: 156,
    stock: 24,
    isFeatured: false,
    isNew: false,
    colors: ['Black', 'White', 'Red'],
  ),
  Product(
    id: '11',
    name: 'Yoga Mat Premium',
    description: 'Non-slip yoga mat with carrying strap, 6mm thickness.',
    category: 'sports',
    price: 29.99,
    originalPrice: 49.99,
    images: [imgP4],
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    rating: 4.3,
    reviewCount: 189,
    stock: 67,
    isFeatured: false,
    isNew: true,
    colors: ['Purple', 'Black', 'Blue', 'Pink'],
  ),
  Product(
    id: '12',
    name: 'Wooden Dining Table',
    description: 'Solid oak wood dining table with room for 6 chairs.',
    category: 'furniture',
    price: 399.99,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    originalPrice: 649.99,
    images: [imgP5],
    rating: 4.7,
    reviewCount: 98,
    stock: 12,
    isFeatured: false,
    isNew: false,
    attributes: {'material': 'Oak Wood', 'capacity': '6 persons'},
  ),
];

const profileButtonsList = [orders, wishList, messages];
const profileButtonImages = [icOrder, icOrder, icMessages];
