import 'package:e_mart/consts/firebase_consts.dart';
import 'package:e_mart/models/product_model.dart';

class ProductSeeder {
  static Future<void> checkAndSeed() async {
    try {
      final snapshot = await firestore.collection(productCollection).limit(1).get();
      if (snapshot.docs.isEmpty) {
        print("Firestore 'products' collection is empty. Seeding data...");
        await _seedProducts();
        print("Seeding completed successfully.");
      } else {
        print("Firestore 'products' collection already has data. Skipping seed.");
      }
    } catch (e) {
      print("Error during seeding: $e");
    }
  }

  static Future<void> _seedProducts() async {
    final batch = firestore.batch();
    
    for (var product in _productsToSeed) {
      final docRef = firestore.collection(productCollection).doc(product.id);
      batch.set(docRef, product.toMap());
    }

    await batch.commit();
  }

  static final List<Product> _productsToSeed = [
    // Featured Products
    Product(
      id: '1',
      name: 'Premium Wireless Headphones',
      description: 'High-quality wireless headphones with noise cancellation and 30-hour battery life.',
      category: 'cellphone',
      price: 79.99,
      originalPrice: 129.99,
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=600'],
      rating: 4.5,
      reviewCount: 320,
      stock: 45,
      isFeatured: true,
      isNew: true,
      colors: ['Black', 'White', 'Blue'],
      attributes: {'brand': 'Sony'},
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Product(
      id: '2',
      name: 'Smart Watch Series 5',
      description: 'Advanced fitness tracking with heart rate monitor and sleep analysis.',
      category: 'cellphone',
      price: 199.99,
      originalPrice: 299.99,
      images: ['https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&q=80&w=600'],
      rating: 4.8,
      reviewCount: 567,
      stock: 32,
      isFeatured: true,
      isNew: true,
      colors: ['Silver', 'Black', 'Gold'],
      attributes: {'brand': 'Apple'},
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Product(
      id: '3',
      name: 'Ergonomic Office Chair',
      description: 'Premium ergonomic chair with lumbar support and adjustable armrests.',
      category: 'furniture',
      price: 249.99,
      originalPrice: 399.99,
      images: ['https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&q=80&w=600'],
      rating: 4.3,
      reviewCount: 245,
      stock: 18,
      isFeatured: true,
      isNew: false,
      colors: ['Black', 'Grey', 'Brown'],
      attributes: {'brand': 'Herman Miller'},
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    ),
    Product(
      id: '4',
      name: 'Professional USB-C Hub',
      description: '7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader.',
      category: 'compAccess',
      price: 49.99,
      originalPrice: 79.99,
      images: ['https://images.unsplash.com/photo-1616424263628-94429e2f6974?auto=format&fit=crop&q=80&w=600'],
      rating: 4.6,
      reviewCount: 189,
      stock: 60,
      attributes: {'brand': 'Anker'},
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isFeatured: true,
      isNew: true,
    ),
    Product(
      id: '5',
      name: 'Sports Running Shoes',
      description: 'Lightweight running shoes with advanced cushioning technology.',
      category: 'sports',
      price: 89.99,
      originalPrice: 139.99,
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=600'],
      rating: 4.4,
      reviewCount: 412,
      stock: 55,
      isFeatured: true,
      isNew: false,
      attributes: {'brand': 'Nike'},
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      sizes: ['6', '7', '8', '9', '10', '11', '12'],
      colors: ['Red', 'Black', 'White'],
    ),
    Product(
      id: '6',
      name: 'Sterling Silver Necklace',
      description: 'Elegant 925 sterling silver necklace with adjustable chain.',
      category: 'jewelery',
      price: 45.99,
      originalPrice: 89.99,
      images: ['https://images.unsplash.com/photo-1599643478524-fb505e3a890b?auto=format&fit=crop&q=80&w=600'],
      rating: 4.7,
      attributes: {'brand': 'Tiffany'},
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      reviewCount: 234,
      stock: 28,
      isFeatured: true,
      isNew: false,
    ),
    Product(
      id: '7',
      name: 'Casual Cotton T-Shirt',
      description: '100% organic cotton, comfortable fit, available in multiple colors.',
      category: 'womenClothing',
      price: 19.99,
      originalPrice: 34.99,
      images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=600'],
      rating: 4.2,
      reviewCount: 145,
      stock: 120,
      attributes: {'brand': 'Zara'},
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      isFeatured: false,
      isNew: true,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Black', 'White', 'Pink', 'Blue'],
    ),
    Product(
      id: '8',
      name: 'Denim Blue Jeans',
      description: 'Classic fit denim jeans with fade-resistant material.',
      category: 'menClothingFashion',
      price: 59.99,
      originalPrice: 99.99,
      images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&q=80&w=600'],
      rating: 4.5,
      attributes: {'brand': "Levi's"},
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      reviewCount: 328,
      stock: 85,
      isFeatured: false,
      isNew: false,
      sizes: ['28', '30', '32', '34', '36', '38'],
      colors: ['Dark Blue', 'Light Blue', 'Black'],
    ),
    Product(
      id: '9',
      name: 'Kids Educational Toy Set',
      description: 'Safe and educational toy set for children ages 3+.',
      category: 'kidtoys',
      price: 34.99,
      originalPrice: 59.99,
      images: ['https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&q=80&w=600'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.6,
      reviewCount: 267,
      stock: 42,
      isFeatured: false,
      isNew: true,
      attributes: {'brand': 'Lego', 'ageRange': '3-8 years', 'pieces': '50+'},
    ),
    Product(
      id: '10',
      name: 'Motorcycle Helmet',
      description: 'DOT certified safety helmet with ventilation system.',
      category: 'automobile',
      price: 129.99,
      originalPrice: 199.99,
      images: ['https://images.unsplash.com/photo-1582281170701-a675034cd415?auto=format&fit=crop&q=80&w=600'],
      attributes: {'brand': 'Bell'},
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.4,
      reviewCount: 156,
      stock: 24,
      isFeatured: false,
      isNew: false,
      colors: ['Black', 'White', 'Red'],
    ),
    Product(
      id: '11',
      name: 'Yoga Mat Premium',
      description: 'Non-slip yoga mat with carrying strap, 6mm thickness.',
      category: 'sports',
      price: 29.99,
      originalPrice: 49.99,
      images: ['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&q=80&w=600'],
      attributes: {'brand': 'Lululemon'},
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.3,
      reviewCount: 189,
      stock: 67,
      isFeatured: false,
      isNew: true,
      colors: ['Purple', 'Black', 'Blue', 'Pink'],
    ),
    Product(
      id: '12',
      name: 'Wooden Dining Table',
      description: 'Solid oak wood dining table with room for 6 chairs.',
      category: 'furniture',
      price: 399.99,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      originalPrice: 649.99,
      images: ['https://images.unsplash.com/photo-1577140917170-285929fb55b7?auto=format&fit=crop&q=80&w=600'],
      rating: 4.7,
      reviewCount: 98,
      stock: 12,
      isFeatured: false,
      isNew: false,
      attributes: {'brand': 'IKEA', 'material': 'Oak Wood', 'capacity': '6 persons'},
    ),
    Product(
      id: '13',
      name: 'Linen Summer Dress',
      description: 'Breathable linen blend dress with a relaxed silhouette for warm days.',
      category: 'womenClothing',
      price: 54.99,
      originalPrice: 89.99,
      images: ['https://images.unsplash.com/photo-1515347619362-75fc1b8e4e6d?auto=format&fit=crop&q=80&w=600'],
      rating: 4.6,
      reviewCount: 214,
      stock: 36,
      isFeatured: true,
      isNew: true,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: ['White', 'Blue', 'Pink'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'Zara', 'material': 'Linen blend', 'fit': 'Relaxed'},
    ),
    Product(
      id: '14',
      name: 'Classic Blazer Jacket',
      description: 'Structured blazer with a clean single-button front and soft lining.',
      category: 'womenClothing',
      price: 74.99,
      originalPrice: 119.99,
      images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=600'],
      rating: 4.4,
      reviewCount: 168,
      stock: 22,
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['Black', 'White', 'Brown'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'H&M', 'material': 'Polyester blend', 'style': 'Business casual'},
    ),
    Product(
      id: '15',
      name: 'Oxford Button-Down Shirt',
      description: 'Soft cotton oxford shirt designed for office days and weekend wear.',
      category: 'menClothingFashion',
      price: 39.99,
      originalPrice: 64.99,
      images: ['https://images.unsplash.com/photo-1596755094514-f87e32f85e2c?auto=format&fit=crop&q=80&w=600'],
      rating: 4.5,
      reviewCount: 286,
      stock: 58,
      isFeatured: true,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['White', 'Blue', 'Black'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'Ralph Lauren', 'material': 'Cotton', 'fit': 'Regular'},
    ),
    Product(
      id: '16',
      name: 'Slim Fit Chinos',
      description: 'Stretch cotton chinos with a tapered leg and everyday comfort.',
      category: 'menClothingFashion',
      price: 49.99,
      originalPrice: 79.99,
      images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&q=80&w=600'],
      rating: 4.3,
      reviewCount: 174,
      stock: 64,
      sizes: ['28', '30', '32', '34', '36', '38'],
      colors: ['Black', 'Brown', 'Grey'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'GAP', 'material': 'Stretch cotton', 'fit': 'Slim'},
    ),
    Product(
      id: '17',
      name: 'Mechanical Keyboard RGB',
      description: 'Compact mechanical keyboard with tactile switches and customizable RGB.',
      category: 'compAccess',
      price: 89.99,
      originalPrice: 129.99,
      images: ['https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&q=80&w=600'],
      rating: 4.8,
      reviewCount: 521,
      stock: 40,
      isFeatured: true,
      isNew: true,
      colors: ['Black', 'White'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'Keychron', 'layout': '75%', 'connection': 'USB-C'},
    ),
    Product(
      id: '18',
      name: 'Wireless Ergonomic Mouse',
      description: 'Rechargeable ergonomic mouse with silent clicks and adjustable DPI.',
      category: 'compAccess',
      price: 34.99,
      originalPrice: 54.99,
      images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=600'],
      rating: 4.4,
      reviewCount: 303,
      stock: 73,
      colors: ['Black', 'Silver'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'Logitech', 'battery': '45 days', 'dpi': '800-2400'},
    ),
    Product(
      id: '19',
      name: 'Remote Control Race Car',
      description: 'Fast rechargeable RC car with shockproof wheels and easy steering.',
      category: 'kidtoys',
      price: 42.99,
      originalPrice: 69.99,
      images: ['https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&q=80&w=600'],
      rating: 4.5,
      reviewCount: 197,
      stock: 38,
      isNew: true,
      colors: ['Red', 'Blue'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'Traxxas', 'ageRange': '6+ years', 'battery': 'Rechargeable'},
    ),
    Product(
      id: '20',
      name: 'Wooden Puzzle Blocks',
      description: 'Colorful wooden blocks that support early learning and motor skills.',
      category: 'kidtoys',
      price: 24.99,
      originalPrice: 39.99,
      images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=600'],
      rating: 4.7,
      reviewCount: 132,
      stock: 51,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'Melissa & Doug', 'ageRange': '2-5 years', 'pieces': '36'},
    ),
    Product(
      id: '21',
      name: 'Car Vacuum Cleaner',
      description: 'Portable high-suction vacuum cleaner for seats, carpets, and trunks.',
      category: 'automobile',
      price: 59.99,
      originalPrice: 89.99,
      images: ['https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=600'],
      rating: 4.2,
      reviewCount: 118,
      stock: 30,
      colors: ['Black'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'Dyson', 'power': '120W', 'filter': 'HEPA'},
    ),
    Product(
      id: '22',
      name: 'Dashboard Phone Mount',
      description: 'Adjustable phone mount with strong suction and 360-degree rotation.',
      category: 'automobile',
      price: 18.99,
      originalPrice: 29.99,
      images: ['https://images.unsplash.com/photo-1601445638532-3c6f6c3aa1d6?auto=format&fit=crop&q=80&w=600'],
      rating: 4.4,
      reviewCount: 267,
      stock: 95,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'Spigen', 'compatibility': '4-7 inch phones', 'rotation': '360 degrees'},
    ),
    Product(
      id: '23',
      name: 'Adjustable Dumbbell Set',
      description: 'Space-saving dumbbell set with quick weight adjustment for home gyms.',
      category: 'sports',
      price: 149.99,
      originalPrice: 219.99,
      images: ['https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&q=80&w=600'],
      rating: 4.7,
      reviewCount: 342,
      stock: 16,
      isFeatured: true,
      colors: ['Black', 'Silver'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'Bowflex', 'weightRange': '5-25 kg', 'material': 'Steel'},
    ),
    Product(
      id: '24',
      name: 'Insulated Sports Bottle',
      description: 'Double-wall stainless steel bottle that keeps drinks cold for hours.',
      category: 'sports',
      price: 21.99,
      originalPrice: 34.99,
      images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&q=80&w=600'],
      rating: 4.6,
      reviewCount: 421,
      stock: 88,
      colors: ['Black', 'Blue', 'Pink'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'Hydro Flask', 'capacity': '750 ml', 'material': 'Stainless steel'},
    ),
    Product(
      id: '25',
      name: 'Pearl Drop Earrings',
      description: 'Minimal pearl earrings with a polished finish for everyday elegance.',
      category: 'jewelery',
      price: 32.99,
      originalPrice: 59.99,
      images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=600'],
      rating: 4.8,
      reviewCount: 203,
      stock: 44,
      isNew: true,
      colors: ['Gold', 'Silver'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'Pandora', 'material': 'Alloy', 'closure': 'Push back'},
    ),
    Product(
      id: '26',
      name: 'Minimal Gold Bracelet',
      description: 'Layer-friendly bracelet with adjustable chain and refined details.',
      category: 'jewelery',
      price: 38.99,
      originalPrice: 74.99,
      images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&q=80&w=600'],
      rating: 4.5,
      reviewCount: 151,
      stock: 37,
      colors: ['Gold'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'Cartier', 'length': '16-20 cm', 'finish': 'Polished'},
    ),
    Product(
      id: '27',
      name: 'Android Tablet 10 Inch',
      description: 'Lightweight tablet with vivid display, long battery life, and stereo speakers.',
      category: 'cellphone',
      price: 229.99,
      originalPrice: 329.99,
      images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=600'],
      rating: 4.4,
      reviewCount: 359,
      stock: 29,
      isFeatured: true,
      colors: ['Black', 'Silver'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'Samsung', 'storage': '128 GB', 'display': '10.1 inch'},
    ),
    Product(
      id: '28',
      name: 'Fast Charging Power Bank',
      description: 'Compact 20000mAh power bank with USB-C fast charging support.',
      category: 'cellphone',
      price: 44.99,
      originalPrice: 69.99,
      images: ['https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&q=80&w=600'],
      rating: 4.6,
      reviewCount: 612,
      stock: 77,
      colors: ['Black', 'White'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'Anker', 'capacity': '20000 mAh', 'ports': 'USB-C, USB-A'},
    ),
    Product(
      id: '29',
      name: 'Modern Floor Lamp',
      description: 'Slim floor lamp with warm lighting for living rooms and bedrooms.',
      category: 'furniture',
      price: 84.99,
      originalPrice: 139.99,
      images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=600'],
      rating: 4.3,
      reviewCount: 96,
      stock: 20,
      colors: ['Black', 'Gold'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'IKEA', 'height': '160 cm', 'bulb': 'E27 LED'},
    ),
    Product(
      id: '30',
      name: 'Storage Coffee Table',
      description: 'Compact coffee table with hidden storage and scratch-resistant finish.',
      category: 'furniture',
      price: 129.99,
      originalPrice: 199.99,
      images: ['https://images.unsplash.com/photo-1532372320572-cda25653a26d?auto=format&fit=crop&q=80&w=600'],
      rating: 4.5,
      reviewCount: 127,
      stock: 14,
      colors: ['Brown', 'White'],
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      attributes: {'brand': 'IKEA', 'material': 'Engineered wood', 'storage': 'Hidden shelf'},
    ),
  ];
}
